easyads:
  section: easyads

gitinfo:
  repositoryUrl: https://github.com/etheriamagazine/hugo-modules
  branch: main
  contentRoot: sky-theme/dev_content

imgproxy:
  enabled: true
  host: https://imgp.etheriamagazine.com/
  sourceStyle: encoded
  format: avif
  process: rs:fit:768
  responsive:
    enabled: true
    srcset:
      - size: 640w
        process: rs:fit:640
      - size: 768w
        process: rs:fit:768
      - size: 1024w
        process: rs:fit:1024
      - size: 1280w
        process: rs:fit:1280

plausible:
  enable: true
  siteScriptId: pa-3sp34HDiAFKjUi4g3DEit
  captureOnLocalhost: true
  proxy: true
  proxyPath: /proxyjs

seo:
  social:
    instagram: etheriamagazine
    x: etheriamagazine
    facebook: etheriamagazine
    pinterest: etheriamagazine
    github: etheriamagazine

skytheme:
  dateLong: :date_long
  dateShort: 02.01.2006
  dateMonthYear: January de 2006
  defaultPostCover: https://placehold.co/1200x750
  reflink:
    errorOn404: true

subscribe:
  action: /subscribe
  title: Newsletter
  textCallToAction: >
   Suscríbete y recibirás los últimos artículos
   de la revista, además de participar en sorteos y
   obtener descuentos.
  privacyPolicyPath: pages/politica-de-privacidad
  privacyPolicyText: Acepto la [política de privacidad]
  inputPlaceholder: "Tu correo electrónico"
  buttonText:
    init: "Suscribirme"
    processing: "Registrando email"
    error: "Error al registrar"
    success: "Registro completado"

