easyads:
  section: easyads

gitinfo:
  repositoryUrl: https://github.com/etheriamagazine/hugo-modules
  branch: main
  contentRoot: sky-theme/dev_content

imgproxy:
  enabled: true
  host: https://imgp.etheriamagazine.com/
  sourceStyle: plain
  responsive:
    defaultSize: 900
    responsiveSizes:
      - 600
      - 900
      - 1200
    processingOptions: rs:fit:%s
    format: avif

plausible:
  enable: true
  domain: etheriamagazine-com.fly.dev
  proxy: true
  proxyPath: /eu-compliance
  optional:
    local: true
    fileDownloads: true
    outboundLinks: true
    error404: true
    customEvents: true

seo:
  social:
    instagram: etheriamagazine
    x: etheriamagazine
    facebook: etheriamagazine
    pinterest: etheriamagazine
    github: etheriamagazine

skytheme:
  dateLong: :date_long
  dateShort: 02.01.2006
  dateMonthYear: January de 2006
  defaultPostCover: https://placehold.co/1200x750
  reflink:
    errorOn404: true

subscribe:
  action: /subscribe
  title: Newsletter
  textCallToAction: >
   Suscríbete y recibirás los últimos artículos
   de la revista, además de participar en sorteos y
   obtener descuentos.
  emailPlaceholder: "Tu correo electrónico"
  privacyPolicyPath: pages/politica-de-privacidad

  submitText: "Suscribirme"

  buttonText:
    init: "Suscribirme"
    processing: "Registrando email"
    error: "Error al registrar"
    success: "Registro completado"


  success:
    buttonText: "Suscribirme"


